# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1946c3d0a8ef562f8380766759f12321c7eede9dbf506e14d2989691245c848e0d1ba8de34aab7e7e18eb580645ecd181714451e60da9dfad57712ceb013aa43

test:
  secret_key_base: d35e295299198cf80649ab158558e897b8c16a7a00f2569f0bd3daefc1abdaa565bd0cba5bc46a364c485d4beb4a13075b29e1d0fb7422f7ad179fec1347bd97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
